name: Publish Book Daily

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    schedule:
        - cron: "0 0 * * *"
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [17.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm run start

            - uses: actions/checkout@v2
            - uses: ncipollo/release-action@v1
              with:
                  artifacts: "*.pdf"
                  token: ${{ secrets.GITHUB_TOKEN }}
